[package]
name = "done"
version = "0.1.1"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "GPL-2.0"
description = "Done is a simple to do app that aims to improve on the existing set of features provided to do apps to deliver the ultimate experience"
homepage = "https://done.edfloreshz.dev/"
documentation = "https://docs.rs/done"
repository = "https://github.com/edfloreshz/done/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gtk4", features = ["v4_4"]}
relm4 = { git = "https://github.com/Relm4/Relm4", branch = "main", version = "0.5.0-beta.1", features = ["all"] }
serde = { version = "1.0.136", features = ["derive"] }
glib = "0.15.11"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
serde_json = "1.0"
anyhow = "1.0.56"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
diesel = { version = "1.4.8", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dirs = "4.0.0"
libset = "0.1.1"
pretty_env_logger = "0.4.0"
log = "0.4.17"
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = { version = "6.4.0", features = ["debug-embed"] }
once_cell = "1.13.0"
libsqlite3-sys = { version = "^0", features = ["bundled"] }
chrono = { version = "0.4.19", features = ["serde"] }
bevy_reflect = "0.8.0"

[build-dependencies]
glib-build-tools = { git = "https://github.com/gtk-rs/gtk-rs-core" }
