[package]
name = "done"
version = "0.1.2"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "GPL-2.0"
description = "Done is a simple to do app that aims to improve on the existing set of features provided to do apps to deliver the ultimate experience"
homepage = "https://done.edfloreshz.dev/"
documentation = "https://docs.rs/done"
repository = "https://github.com/edfloreshz/done/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4.0"
strum_macros = "0.24.3"
i18n-embed-fl = "0.6.4"
once_cell = "1.13.0"
derive-new = "0.5.9"
reqwest = "0.11.13"
sysinfo = "0.27.5"
serde_json = "1.0"
anyhow = "1.0.56"
strum = "0.24.1"
tonic = "0.8.2"
glib = "0.16.2"
log = "0.4.17"

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread"]

[dependencies.chrono]
version = "0.4.23"
features = ["serde"]

[dependencies.relm4]
version = "0.5.0-rc.1"
features = ["macros", "libadwaita"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]

[dependencies.libadwaita]
version = "0.2.1"
features = ["v1_2"]

[dependencies.gettext-rs]
version = "0.7"
features = ["gettext-system"]

[dependencies.rust-embed]
version = "6.4.0"
features = ["debug-embed"]

[dependencies.i18n-embed]
version = "0.13.4"
features = ["fluent-system", "desktop-requester"]

[dependencies.libset]
git = "https://github.com/edfloreshz/libset"
branch = "beta"

[dependencies.directories]
git = "https://github.com/edfloreshz/directories-rs"

[dependencies.proto_rust]
git = "https://github.com/done-devel/proto-rust"

[build-dependencies]
glib-build-tools = "0.16.3"
