[package]
name = "done"
version = "0.1.2"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "GPL-2.0"
description = "Done is a simple to do app that aims to improve on the existing set of features provided to do apps to deliver the ultimate experience"
homepage = "https://done.edfloreshz.dev/"
documentation = "https://docs.rs/done"
repository = "https://github.com/edfloreshz/done/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
rust-embed = { version = "6.4.0", features = ["debug-embed"] }
relm4 = { git = "https://github.com/Relm4/Relm4", branch="async-factories", features = ["macros", "libadwaita"] }
done_core = { path = "core" }
i18n-embed-fl = "0.6.4"
once_cell = "1.13.0"
serde_json = "1.0"
anyhow = "1.0.56"
libset = "0.1.1"
glib = "0.16.2"
dirs = "4.0.0"
pretty_env_logger = "0.4.0"
log = "0.4.17"
async-std = "1.12.0"

[build-dependencies]
glib-build-tools = { git = "https://github.com/gtk-rs/gtk-rs-core" }
