[package]
name = "done"
version = "0.1.0"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "GPL-2.0"
description = "Done is a simple to do app that aims to improve on the existing set of features provided to do apps to deliver the ultimate experience"
homepage = "https://done.edfloreshz.dev/"
documentation = "https://docs.rs/done"
repository = "https://github.com/edfloreshz/done/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.15.11"
relm4 = { git = "https://github.com/Relm4/Relm4", branch = "next", version = "0.5.0-beta.1", features = ["all"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.56"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tracker = "0.1.1"
diesel = { version = "1.4.8", features = ["sqlite"] }
diesel_migrations = "1.4.0"
dirs = "4.0.0"
libset = "0.1.1"
#tokio = { version = "1.17.0", features = ["full"] }
#once_cell = "1.10.0"
#chrono = "0.4.19"
#cascade = "1.0.0"

