[package]
name = "done_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
anyhow = "1.0.66"
uuid = { version = "1.2.1", features = ["v4"] }
tonic = "0.8.2"
prost = "0.11.0"
strum = "0.24.1"
strum_macros = "0.24.3"

[build-dependencies]
tonic-build = "0.8.2"